# Generated by Django 2.1.5 on 2019-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=16)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=16, null=True)),
                ('password', models.CharField(max_length=16, null=True)),
                ('ssh_key', models.TextField(max_length=30, null=True)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usage', models.ManyToManyField(to='webapp.Host')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='hosts',
            field=models.ManyToManyField(to='webapp.Host'),
        ),
    ]
